rabbitmq:
  enabled: true
  replicaCount: 2
  hosts:
    management: uat-moti-rabbitmq.apps.silver.devops.gov.bc.ca
    stomp: uat-moti-rabbitmq-stomp.apps.silver.devops.gov.bc.ca

allowedNamespace:
  - name: fdf5df
    environment: test
