repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # pragma: allowlist secret; frozen: v6.0.0
  hooks:
  - id: check-case-conflict
  - id: check-executables-have-shebangs
    files: \.sh
  - id: check-json
  # - id: check-vcs-permalinks
  - id: check-yaml
    exclude: ^helm
  - id: check-ast
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/Yelp/detect-secrets
  rev: 68e8b45440415753fff70a312ece8da92ba85b4a  # pragma: allowlist secret; frozen: v1.5.0
  hooks:
  - id: detect-secrets
    args: [--baseline, .secrets.baseline]
    exclude: package.lock.json

exclude: ^(CHANGELOG\.md)$
