{{- if .Values.rabbitmq.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "main.fullname" . }}
  labels:
    {{- include "main.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: {{ .Values.rabbitmq.nameOverride }}
  minReplicas: {{ .Values.rabbitmq.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.rabbitmq.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.rabbitmq.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.rabbitmq.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.rabbitmq.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.rabbitmq.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
