apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: moti-rabbitmq
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: moti-rabbitmq
      app.kubernetes.io/instance: moti-message-broker
