{{- $adminSecretName := "rabbitmq-admin" }}
{{- $adminSecret := (lookup "v1" "Secret" .Release.Namespace $adminSecretName ) }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $adminSecretName }}
  labels: {{ include "main.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  {{- if $adminSecret }}
  rabbitmq-password: {{ index $adminSecret.data "rabbitmq-password" }}
  {{- else }}
  rabbitmq-password: {{ (randAlphaNum 32) | b64enc }}
  {{- end }}
