name: Build RabbitMQ image - Managed

on:
  push:
    branches:
    - main
    paths:
    - dockerfiles/**
    - .github/workflows/build-push-rabbitmq-managed.yml
  workflow_dispatch:


env:
  REGISTRY: ghcr.io
  IMAGE_NAME: bcgov/bitnami-rabbitmq

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-push-4_3-debian_12:
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    env:
      TAG_PREFIX: 4.3-debian-12
    steps:
    - uses: hmarr/debug-action@f7318c783045ac39ed9bb497e22ce835fdafbfe6
    - uses: actions/checkout@7

    - name: Setup Tools
      uses: ./.github/actions/setup-tools

    - name: Set build timestamp
      run: echo "BUILD_TIME=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

    - name: Build and Push
      uses: egose/actions/docker-build-push@14290eef7e6eb130b98d2a67aa663da9832fe0cc
      with:
        registry-url: ${{ env.REGISTRY }}
        registry-username: ${{ github.actor }}
        registry-password: ${{ secrets.GITHUB_TOKEN }}
        image-name: ${{ env.IMAGE_NAME }}
        docker-context: dockerfiles/4.3/debian-12
        docker-file: dockerfiles/4.3/debian-12/Dockerfile
        metadata-tags: |
          ${{ env.TAG_PREFIX }}-${{ env.BUILD_TIME }}

    - name: Fetch RabbitMQ Version
      id: fetch_version
      run: |
        VERSION=$(docker run --rm --entrypoint rabbitmqctl ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG_PREFIX }}-${{ env.BUILD_TIME }} version)
        echo "RabbitMQ version: $VERSION"
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Generate Dockerfile
      run: |
        echo "FROM ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG_PREFIX }}-${{ env.BUILD_TIME }}" > Dockerfile

    - name: Build and Push Docker image
      uses: egose/actions/docker-build-push@14290eef7e6eb130b98d2a67aa663da9832fe0cc
      with:
        registry-url: ${{ env.REGISTRY }}
        registry-username: ${{ github.actor }}
        registry-password: ${{ secrets.GITHUB_TOKEN }}
        image-name: ${{ env.IMAGE_NAME }}
        docker-context: .
        docker-file: Dockerfile
        metadata-tags: |
          latest
          ${{ env.VERSION }}
